# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

selinv2julia <- function(nnodes, nnz, colptr_, rowind_, nzval_) {
    .Call('sInverse_selinv2julia', PACKAGE = 'sInverse', nnodes, nnz, colptr_, rowind_, nzval_)
}

